### ISSUE TITLE
How to generate hyperedge？

### ISSUE THREAD

**Issue by huzh8** [sheldonresearch/MGCN#1]
Hi, thank you for the great repo.
I noticed that you connect each node and its 10 hop neighbors with one hyperedge in your paper.I think that may be the characteristic of large networks,because we usually don't use such high-order neighbors.
Would you mind sharing the code for generating hyperedge ?

**Comment by sheldonresearch** [comment]
Hi, thank you for your requests.

N-hop neighbors can be easily obtained if you use the N power of the adjacent matrix.

for example:

```
A # is the adjacent matrix
H=A@A@A...@A
```
